<?php

namespace Database\Seeders;

use App\Models\Movie;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MovieSeeder extends Seeder
{
    public function run(): void
    {
        Movie::query()->forceDelete();

        $movies = $this->getMovieData();

        foreach ($movies as $movie) {
            Movie::create(array_merge($movie, [
                'slug' => Str::slug($movie['title'] . '-' . date('Y')),
            ]));
        }

        $this->command->info('✓ Movies seeded: ' . count($movies));
    }

    private function getMovieData(): array
    {
        return [

            // Now Showing
            [
                'tmdb_id'      => 1022789,
                'title'        => 'Inside Out 2',
                'original_title' => 'Inside Out 2',
                'synopsis'     => 'Riley memasuki masa remaja dan emosi-emosi lamanya — Joy, Sadness, Anger, Fear, dan Disgust — harus berhadapan dengan emosi baru yang lebih kompleks: Anxiety, Envy, Ennui, dan Embarrassment.',
                'poster'       => 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
                'backdrop'     => 'https://image.tmdb.org/t/p/w1280/xg27NrXi7VXCGUr7MlcbgrrmR9I.jpg',
                'trailer_url'  => 'https://www.youtube.com/watch?v=LEjhY15eCx0',
                'genres'       => ['Animation', 'Adventure', 'Comedy', 'Family'],
                'duration'     => 100,
                'age_rating'   => 'SU',
                'language'     => 'id',
                'director'     => 'Kelsey Mann',
                'cast'         => ['Amy Poehler', 'Maya Hawke', 'Kensington Tallman', 'Liza Lapira', 'Tony Hale'],
                'production_companies' => ['Pixar Animation Studios', 'Walt Disney Pictures'],
                'release_date' => '2024-06-14',
                'vote_average' => 7.7,
                'vote_count'   => 3842,
                'status'       => 'now_showing',
                'is_featured'  => true,
            ],
            [
                'tmdb_id'      => 653346,
                'title'        => 'Kingdom of the Planet of the Apes',
                'original_title' => 'Kingdom of the Planet of the Apes',
                'synopsis'     => 'Ratusan tahun setelah pemerintahan Caesar, sebuah kerajaan kera baru bangkit. Noa, kera muda yang berani, memulai perjalanan epik dan bertemu dengan Mae, manusia misterius.',
                'poster'       => 'https://image.tmdb.org/t/p/w500/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
                'backdrop'     => 'https://image.tmdb.org/t/p/w1280/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
                'trailer_url'  => 'https://www.youtube.com/watch?v=XRFSaRjSMf4',
                'genres'       => ['Action', 'Sci-Fi', 'Adventure'],
                'duration'     => 145,
                'age_rating'   => '13+',
                'language'     => 'id',
                'director'     => 'Wes Ball',
                'cast'         => ['Owen Teague', 'Freya Allan', 'Kevin Durand', 'Peter Macon', 'William H. Macy'],
                'production_companies' => ['20th Century Studios', 'Ingenious Media'],
                'release_date' => '2024-05-10',
                'vote_average' => 6.8,
                'vote_count'   => 2941,
                'status'       => 'now_showing',
                'is_featured'  => true,
            ],
            [
                'tmdb_id'      => 519182,
                'title'        => 'Despicable Me 4',
                'original_title' => 'Despicable Me 4',
                'synopsis'     => 'Gru dan keluarganya kembali beraksi! Kali ini Gru menghadapi ancaman baru dari penjahat Maxime Le Mal dan pasangannya Valentina, sementara Minions punya misi seru tersendiri.',
                'poster'       => 'https://image.tmdb.org/t/p/w500/wWba3TaojhK7NdycyUplzdZ17nY.jpg',
                'backdrop'     => 'https://image.tmdb.org/t/p/w1280/lgkgd4AEPgBMQenGDNt0V8OqRft.jpg',
                'trailer_url'  => 'https://www.youtube.com/watch?v=qcGpBmYRjPM',
                'genres'       => ['Animation', 'Comedy', 'Family'],
                'duration'     => 95,
                'age_rating'   => 'SU',
                'language'     => 'id',
                'director'     => 'Chris Renaud',
                'cast'         => ['Steve Carell', 'Kristen Wiig', 'Will Ferrell', 'Joey King', 'Miranda Cosgrove'],
                'production_companies' => ['Universal Pictures', 'Illumination'],
                'release_date' => '2024-07-03',
                'vote_average' => 7.1,
                'vote_count'   => 1876,
                'status'       => 'now_showing',
                'is_featured'  => true,
            ],
            [
                'tmdb_id'      => 748783,
                'title'        => 'The Garfield Movie',
                'original_title' => 'The Garfield Movie',
                'synopsis'     => 'Garfield, kucing oranye pemalas yang gemar lasagna, memulai petualangan di luar rumah yang mengubah hidupnya setelah bertemu kembali dengan ayahnya yang sudah lama hilang.',
                'poster'       => 'https://image.tmdb.org/t/p/w500/p6AbOJvMQhBmffd0PIv0KqsLo0D.jpg',
                'backdrop'     => 'https://image.tmdb.org/t/p/w1280/t5zSSF5BPpCaByRMlC6h3BMRvQL.jpg',
                'trailer_url'  => 'https://www.youtube.com/watch?v=R3BNlFwZAFI',
                'genres'       => ['Animation', 'Comedy', 'Family', 'Adventure'],
                'duration'     => 101,
                'age_rating'   => 'SU',
                'language'     => 'id',
                'director'     => 'Mark Dindal',
                'cast'         => ['Chris Pratt', 'Samuel L. Jackson', 'Hannah Waddingham', 'Ving Rhames'],
                'production_companies' => ['Sony Pictures Animation', 'DNEG Animation'],
                'release_date' => '2024-05-24',
                'vote_average' => 6.5,
                'vote_count'   => 1423,
                'status'       => 'now_showing',
                'is_featured'  => false,
            ],
            [
                'tmdb_id'      => 573435,
                'title'        => 'Bad Boys: Ride or Die',
                'original_title' => 'Bad Boys: Ride or Die',
                'synopsis'     => 'Detektif Miami Mike Lowrey dan Marcus Burnett kembali! Kali ini keduanya menjadi buronan setelah difitnah dalam kasus korupsi besar yang mengancam karier dan hidup mereka.',
                'poster'       => 'https://image.tmdb.org/t/p/w500/oGythE98MYleE6mZlGs5oBMkQ1l.jpg',
                'backdrop'     => 'https://image.tmdb.org/t/p/w1280/1HGANudg5MYmTHaJdHNNoJAvjkK.jpg',
                'trailer_url'  => 'https://www.youtube.com/watch?v=qj1xUkFCOho',
                'genres'       => ['Action', 'Comedy', 'Crime'],
                'duration'     => 115,
                'age_rating'   => '17+',
                'language'     => 'id',
                'director'     => 'Adil El Arbi',
                'cast'         => ['Will Smith', 'Martin Lawrence', 'Vanessa Hudgens', 'Alexander Ludwig'],
                'production_companies' => ['Columbia Pictures', 'Don Simpson/Jerry Bruckheimer Films'],
                'release_date' => '2024-06-07',
                'vote_average' => 7.0,
                'vote_count'   => 1654,
                'status'       => 'now_showing',
                'is_featured'  => false,
            ],
            [
                'tmdb_id'      => 976573,
                'title'        => 'Elemental',
                'original_title' => 'Elemental',
                'synopsis'     => 'Di kota Elemental yang dihuni api, air, tanah, dan udara, Api bernama Ember bertemu dengan Air bernama Wade. Pertemuan tak terduga ini menantang semua yang diyakini Ember tentang dunia.',
                'poster'       => 'https://image.tmdb.org/t/p/w500/6oH378KUfgKm87SH7GKaGHFoVMl.jpg',
                'backdrop'     => 'https://image.tmdb.org/t/p/w1280/sCWqFQFKnBOmEFBWIiIoFEnPVfE.jpg',
                'trailer_url'  => 'https://www.youtube.com/watch?v=hXzcyx9V0xw',
                'genres'       => ['Animation', 'Romance', 'Comedy', 'Family'],
                'duration'     => 101,
                'age_rating'   => 'SU',
                'language'     => 'id',
                'director'     => 'Peter Sohn',
                'cast'         => ['Leah Lewis', 'Mamoudou Athie', 'Ronnie del Carmen', 'Shila Ommi'],
                'production_companies' => ['Pixar Animation Studios', 'Walt Disney Pictures'],
                'release_date' => '2024-06-16',
                'vote_average' => 7.4,
                'vote_count'   => 3218,
                'status'       => 'now_showing',
                'is_featured'  => false,
            ],

            // Coming Soon
            [
                'tmdb_id'      => 558449,
                'title'        => 'Gladiator II',
                'original_title' => 'Gladiator II',
                'synopsis'     => 'Bertahun-tahun setelah peristiwa di film pertama, Lucius muda dipaksa masuk ke Colosseum setelah tanah airnya ditaklukkan oleh Kaisar Roma yang zalim.',
                'poster'       => 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
                'backdrop'     => 'https://image.tmdb.org/t/p/w1280/euYIwmwkmz95mnXvufEJeKkiMoH.jpg',
                'trailer_url'  => 'https://www.youtube.com/watch?v=Cf_oPFuZXQE',
                'genres'       => ['Action', 'Drama', 'Adventure'],
                'duration'     => 148,
                'age_rating'   => '17+',
                'language'     => 'id',
                'director'     => 'Ridley Scott',
                'cast'         => ['Paul Mescal', 'Pedro Pascal', 'Denzel Washington', 'Connie Nielsen'],
                'production_companies' => ['Paramount Pictures', 'Scott Free Productions'],
                'release_date' => now()->addDays(20)->format('Y-m-d'),
                'vote_average' => null,
                'vote_count'   => null,
                'status'       => 'coming_soon',
                'is_featured'  => true,
            ],
            [
                'tmdb_id'      => 762441,
                'title'        => 'A Quiet Place: Day One',
                'original_title' => 'A Quiet Place: Day One',
                'synopsis'     => 'Kisah hari pertama invasi makhluk yang berburu berdasarkan suara. Sam berada di New York saat chaos dimulai dan harus bertahan hidup dalam keheningan mutlak di kota metropolitan.',
                'poster'       => 'https://image.tmdb.org/t/p/w500/yrpPYKijwdMHyTGIOd1iK1h0Xno.jpg',
                'backdrop'     => 'https://image.tmdb.org/t/p/w1280/2Nti3gYAX513wvaz44yqBGIXysX.jpg',
                'trailer_url'  => 'https://www.youtube.com/watch?v=rrBOPH5HaFw',
                'genres'       => ['Horror', 'Sci-Fi', 'Thriller'],
                'duration'     => 99,
                'age_rating'   => '17+',
                'language'     => 'id',
                'director'     => 'Michael Sarnoski',
                'cast'         => ['Lupita Nyong\'o', 'Joseph Quinn', 'Alex Wolff', 'Djimon Hounsou'],
                'production_companies' => ['Paramount Pictures', 'Platinum Dunes'],
                'release_date' => now()->addDays(35)->format('Y-m-d'),
                'vote_average' => null,
                'vote_count'   => null,
                'status'       => 'coming_soon',
                'is_featured'  => false,
            ],
            [
                'tmdb_id'      => 519181,
                'title'        => 'Deadpool & Wolverine',
                'original_title' => 'Deadpool & Wolverine',
                'synopsis'     => 'Wade Wilson alias Deadpool merekrut Wolverine yang enggan untuk petualangan lintas alam semesta yang gila. Film Marvel pertama yang mendapat rating R.',
                'poster'       => 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
                'backdrop'     => 'https://image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
                'trailer_url'  => 'https://www.youtube.com/watch?v=73_1biulkYk',
                'genres'       => ['Action', 'Comedy', 'Superhero'],
                'duration'     => 127,
                'age_rating'   => '17+',
                'language'     => 'id',
                'director'     => 'Shawn Levy',
                'cast'         => ['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin', 'Matthew Macfadyen'],
                'production_companies' => ['Marvel Studios', 'Maximum Effort'],
                'release_date' => now()->addDays(50)->format('Y-m-d'),
                'vote_average' => null,
                'vote_count'   => null,
                'status'       => 'coming_soon',
                'is_featured'  => true,
            ],
            [
                'tmdb_id'      => 1100782,
                'title'        => 'Speak No Evil',
                'original_title' => 'Speak No Evil',
                'synopsis'     => 'Pasangan Amerika menerima undangan makan malam dari keluarga yang mereka temui di liburan. Apa yang tampak sebagai pertemuan ramah perlahan berubah menjadi mimpi buruk yang mencekam.',
                'poster'       => 'https://image.tmdb.org/t/p/w500/64xAMdCdEfVWqDDiVJQDL38DGzh.jpg',
                'backdrop'     => 'https://image.tmdb.org/t/p/w1280/9oBxYxNoBPHUCb6gMmZYI8QKlf6.jpg',
                'trailer_url'  => 'https://www.youtube.com/watch?v=IamkqX0fRBg',
                'genres'       => ['Horror', 'Thriller', 'Mystery'],
                'duration'     => 110,
                'age_rating'   => '17+',
                'language'     => 'id',
                'director'     => 'James Watkins',
                'cast'         => ['James McAvoy', 'Mackenzie Davis', 'Scoot McNairy', 'Aisling Franciosi'],
                'production_companies' => ['Universal Pictures', 'Blumhouse'],
                'release_date' => now()->addDays(15)->format('Y-m-d'),
                'vote_average' => null,
                'vote_count'   => null,
                'status'       => 'coming_soon',
                'is_featured'  => false,
            ],

            // Film Indonesia
            [
                'tmdb_id'      => null,
                'title'        => 'Agak Laen',
                'original_title' => 'Agak Laen',
                'synopsis'     => 'Empat sahabat penjaga wahana hantu di sebuah mal menemukan mayat di wahana mereka. Panik, mereka menyembunyikan mayat itu — yang justru memicu serangkaian petaka lucu tak terduga.',
                'poster'       => 'https://upload.wikimedia.org/wikipedia/id/3/3d/Poster_film_Agak_Laen.jpg',
                'backdrop'     => null,
                'trailer_url'  => 'https://www.youtube.com/watch?v=example',
                'genres'       => ['Comedy', 'Horror'],
                'duration'     => 106,
                'age_rating'   => '13+',
                'language'     => 'id',
                'director'     => 'Muhadkly Acho',
                'cast'         => ['Bene Dion', 'Oki Rengga', 'Frequency Bre', 'Boris Bokir'],
                'production_companies' => ['Kawan Kawan Media'],
                'release_date' => now()->subDays(30)->format('Y-m-d'),
                'vote_average' => 8.2,
                'vote_count'   => 5621,
                'status'       => 'now_showing',
                'is_featured'  => true,
            ],
            [
                'tmdb_id'      => null,
                'title'        => 'Ipar adalah Maut',
                'original_title' => 'Ipar adalah Maut',
                'synopsis'     => 'Drama psikologis tentang pernikahan yang terancam hancur ketika adik ipar mulai menunjukkan ketertarikan terlarang. Diangkat dari kisah nyata yang menghebohkan.',
                'poster'       => null,
                'backdrop'     => null,
                'trailer_url'  => 'https://www.youtube.com/watch?v=example2',
                'genres'       => ['Drama', 'Thriller'],
                'duration'     => 113,
                'age_rating'   => '17+',
                'language'     => 'id',
                'director'     => 'Rizal Mantovani',
                'cast'         => ['Reza Rahadian', 'Davina Karamoy', 'Acha Septriasa'],
                'production_companies' => ['MD Entertainment'],
                'release_date' => now()->subDays(10)->format('Y-m-d'),
                'vote_average' => 7.9,
                'vote_count'   => 2847,
                'status'       => 'now_showing',
                'is_featured'  => false,
            ],
        ];
    }
}
